### ISSUE TITLE
Work boats can enter ocean before Astronomy

### ISSUE THREAD

**Issue by bernd-das-brot** [Thalassicus/cep-bnw#106]
(v. 3.12.1) Work boats can enter ocean before Astronomy again.

**Comment by GrantSP** [comment]
I think I made some comment about this before in the forum, but can't find where it is. I believe this is an intended change but, like you, I am beginning to think this is not a good idea.
I had seen the AI abuse this for quite some time and hadn't done so personally, I did so last night and it is just too easy to map out the world before anyone else.
Since your work boats only cost 80Gold you can buy lots and it doesn't matter if they get caught by barbarians. But, with their 4 movement they can outpace just about anything on the water. Add to that the barbarians can't follow you into ocean tiles and you _CAN_ avoid them and see the globe before anyone else, as I did last night.

We should revert this.

**Comment by bernd-das-brot** [comment]
Never thought this could be intended! Definitly this should be reversed. Work boats as cheap, early and unattackable ocean-crossers is really not fun, nor does it make any sense.

**Comment by stackpoint** [comment]
The merits of ocean travel with boats should be discussed on the forums. Specifically ocean traveling workboats and obsolete ships gaining the ability to traverse the ocean with astronomy researched.
