### ISSUE TITLE
[3.12.2] Hagia Sohia does not give faith per specialist

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#129]
Tested with 3.12.2+Ingame Editor (cache cleared etc. prior to test).

The Hagia Sophia gives +1 faith but not the faith from specialists.

Confirmed in different games and from other users on civfanatics.

\Skodkim

**Comment by stackpoint** [comment]
Statue of Liberty is not giving extra production per specialist? This is strange since CEP is using a vanilla table and the SoL ability is from vanilla.

**Comment by stackpoint** [comment]
I don't think the vanilla game recognizes yields other than science, gold and production for specialist yields.

Culture is handled using CulturePerTurn so that doesn't count and the YieldLibrary doesn't seem to have anything to SpecialistYields.

We should probably change the effect of the Hagia Sophia for now.

**Comment by skodkim** [comment]
Sorry, I just tested Again and in fact the Statue of Liberty does Work (It's just hardto keep track of because of the bug concerning yields in citi view).

Deleted the info about this in post above.

\Skodkim

**Comment by skodkim** [comment]
How about giving Shrines and temples +1 faith for now (with Hagia Sofia)?

\Skodkim

**Comment by stackpoint** [comment]
Hagia Sophia should be fixed. Further problems should be brought up [here](https://github.com/Thalassicus/cep-bnw/issues/179).
