### ISSUE TITLE
Germany's Bismarck UA bug

### ISSUE THREAD

**Issue by a9455945** [Thalassicus/cep-bnw#139]
Hanseatic League claims to add 3 extra votes to the world council but it does not. It only doubles strategic resources.

**Comment by stackpoint** [comment]
I checked the source code briefly and it looks like the field ExtraLeagueVotes in the Leaders table is just window dressing and is never used. The ExtraLeagueVotes field in the Buildings table seems to be the only area where you can get extra votes.

It looks like a dummy building with the ExtraLeagueVotes field is needed for Germany.

**Comment by stackpoint** [comment]
Nevermind, I'm not sure what I was thinking when I wrote this. HANSEATIC_LEAGUE was a dummy building already coded but not granted anywhere. I'll write some code to do this.

**Comment by stackpoint** [comment]
Looks like code is written to grant the building but it doesn't seem to be working.

**Comment by stackpoint** [comment]
Fixed here: https://github.com/Thalassicus/cep-bnw/commit/90aa9ed8593847f5a807dc6038d087a1a685bbdb

**Comment by GrantSP** [comment]
Just something to keep in mind if this ever gets raised again, perhaps by someone with a little less knowledge of how it is constructed.
Since the UA is actually given via a dummy building, on the World Congress panel the tooltip to show where the votes are coming from says there are 3 votes from a World Wonder. This is because the dummy building is a 'Palace'.
At least that is what I think is going on.

**Comment by stackpoint** [comment]
I believe it's because ExtraLeagueVotes is only used with the Forbidden Palace wonder.
