### ISSUE TITLE
Most pressing need

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#173]
If I may be so bold as to dictate the decision processes for the team.
The most pressing need I see for this mod at the moment is the lua code framework.

YieldLibrary, ToolTipWriter etc.

If I could illustrate it this way:
If the mod was a house some of us are looking at placing furniture or painting walls while there still exists missing walls and plumbing.
Some of the suggested changes need the underlying code in place so that the less savvy coders (like me) can just use the framework as it stands without the worry of wondering if the changes will actually work as expected.

I appreciate that these sort of changes will need a bit of intensive work but once its done, its done!

If I am speaking out of class, please feel free to close this issue.

**Comment by skodkim** [comment]
I have to say that I support you here, especially on the yield library. The underlying framework needs to be on before you can build anything good. Couldn't have said it better myself. 

In my local copy of the mod I like to try out new effects for buildings, wonders, policies etc but many are broken. That also includes existing ones.

Furthermore I've been spending way to much time just trying to find out whether effects actually work or not as the display in the city window is bugged, probably because of the yield library.

I actually feel a bit bad for raising this because I know I can't do something about it myself and I know it's a lot of work.

\Skodkim

On 2. feb. 2014 07.00.58 CET, GrantSP notifications@github.com wrote:

> If I may be so bold as to dictate the decision processes for the team.
> The most pressing need I see for this mod at the moment is the lua code
> framework.
> 
> YieldLibrary, ToolTipWriter etc.
> 
> If I could illustrate it this way:
> If the mod was a house some of us are looking at placing furniture or
> painting walls while there still exists missing walls and plumbing.
> Some of the suggested changes need the underlying code in place so that
> the less savvy coders (like me) can just use the framework as it stands
> without the worry of wondering if the changes will actually work as
> expected.
> 
> I appreciate that these sort of changes will need a bit of intensive
> work but once its done, its done!
> 
> If I am speaking out of class, please feel free to close this issue.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/173

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by GrantSP** [comment]
I make it a habit of speaking my mind. Unfortunately, I often have to
retract comments due to not being aware of all details.
Let me state upfront this is not to be seen as a dig in the guts to anyone.

**Comment by stackpoint** [comment]
After the policy update is released, the next things (in terms of game balance) to look at would probably be the problems of (relatively) recent unit lines (upgrade paths) changes and the overhauled religious beliefs systems that people on the forums feel need to be reviewed. This would need to be handled by @Thalassicus since I don't think anybody handles major game balancing stuff except him.

**Comment by Kakafika** [comment]
I was going to start a post on civfanatics about this issue a week ago before I noticed this here.

I agree that working on the yield library would greatly improve the modded experience. As it is now, several of the fun, game-changing UAs/UBs/wonders are duds. I dislike both that I have fewer choices myself and that the AI still wastes production on these wonders. The upside is that I've had the chance to try out several of the vanilla scenarios =D

Like GrantSP and skodim, let me make clear that with this request all I can offer is my thanks XD  As such, I am perfectly happy to wait until life gives you an opportunity to look into this =)

**Comment by EricB1** [comment]
With respect to the belief system balance, the biggest issue that I see needing correcting is the beliefs that give culture.  The one that gives culture per city following your religion and the one giving culture per citizens following your religion.  Those 2 give way too much culture.

I went through and re-balanced beliefs myself about a week ago (just for myself) and those were the biggest ones.  There were a few other minor ones.  Some pantheon beliefs are rarely ever useful and need slight buffs.  Overall, it's not too bad.  I see the policy balance (especially the ideologies) and the leader uniques balance as bigger priorities.  Also, like has been mentioned some of the upgrades are just weird like Destroyers upgrading to Carriers and Arquebusiers upgrading to Gatling Guns.

**Comment by GrantSP** [comment]
I'm going to bump this issue again now I see @Thalassicus is active again.

`<rant>`

The lua code is in desperate need of updating. I have no confidence that any XML/sql code that draws on a table to do with yields will **actually** display the correct yield.
I would go so far as to say that much of the code could do with a thorough revamp and possibly a culling. As it is now my system takes a noticeable performance hit when running the mod, is there some way to optimize the calculations made by all that code?
For those of us with no practical lua skills it is next to impossible to make heads or tails of what is happening.
If the framework is in place then **anyone** should be able to come along and add to the functionality.

`</rant>`

**Comment by Thalassicus** [comment]
I managed to fix the performance problem in issue #252. It looks like the rest is being addressed in #179.
