### ISSUE TITLE
Some bugs, some solutions and some questions

### ISSUE THREAD

**Issue by Slogun** [Thalassicus/cep-bnw#178]
Hi, i am currently translating this whole crazy mod in French. That's a lot of work, especially because i have low coding skills (it took me 1 whole day to translate half the leaders.sql, but i checked everything and i really want to stay as close as possible to the original french texts. Moreover, i inserted a few [ICON_xxxx] here and there)

***\* leaders.sql ****
- TRAIT_GATEWAY_TO_AFRICA has to be renamed to GATEWAY_AFRICA
- obsolete or wrong keys :
  TRAIT_GAO_MILITIA
  TRAIT_LAND_TRADE_GOLD
  TRAIT_RAZE_AND_HORSES
  TRAIT_AMERICAN_DREAM
  TRAIT_SEVEN_CITIES
  TRAIT_SCOURGE_OF_GOD
  TRAIT_AMSTERDAM_BOURSE
- unknown keys (if you can explain what they are supposed to do, please)
  MIGRATE_WITHIN
  MIGRATE_IN
  MIGRATE_OUT
  CITY_CAPTURE_YIELD

**Comment by GrantSP** [comment]
TRAIT_GATEWAY_TO_AFRICA has already been fixed. (it seems the French are out in force at the moment. This was found as a result of a French translation error)

The next list of TXT_KEYs are not used at the moment. They are kept simply because of the fluid nature of the Leader changes. Today they are obsolete, tomorrow they may be used.

The unknown keys are from an attempt to introduce immigration into the mod. It was not well received and therefore these keys also are not used at the moment.

There should be no harm in leaving them in and if you wish to not translate them at this time your game should suffer no ill effects.

CITY_CAPTURE_YIELD is still referenced by some lua code so you might like to do that one just in case.
