### ISSUE TITLE
"Units may cross mountains"

### ISSUE THREAD

**Issue by Slogun** [Thalassicus/cep-bnw#188]
Dido's (Carthage) units are supposed to be able to cross mountains. Does this ability really work ? If so, how does it work ?

(Communitas Communitas AI and Tools & Communitas Enhanced Gameplay loaded)

**Comment by stackpoint** [comment]
This is either a text error or the ability might have been accidentally removed. Not sure which.

**Comment by Slogun** [comment]
I'm the only CEP tester or what ? :smile:

**Comment by GrantSP** [comment]
No you're the only tester who takes the time to note these errors and
notify us. ;)

On 14 February 2014 06:58, Slogun notifications@github.com wrote:

> I'm the only CEP tester or what ? [image: :smile:]
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/188#issuecomment-35019060
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by GrantSP** [comment]
The ability does work but the description is a little vague. The ability only kicks in **AFTER** a Great General has been generated. The idea I guess is to re-create the 'Hannibal crossing the Alps thing'.

So, the problem is the text, which I will correct now. However there is a problem in the vanilla path-finding that you might like to be mindful of.
If you send a unit to a spot, say 5 or 6 turns away, and there are mountains in the path. The pathfinding routine will cross them but not take into account the 50% attrition damage the unit will take each turn it ends on a mountain. I have had the little piece of "unit died music" play and seen the notification popup and wonder: "who just attacked me?", only to find it is my worker out to build that plantation that died in the mountains on the way there.
What this means is, if you play as Carthage, be prepared for a lot of micro-managed unit placement. You will have to send units to as close as possible to the location avoiding mountains and either move them over yourself, avoiding the problem of ending your turn on the top. Or take the long way around as you would as another civ.
