### ISSUE TITLE
The Netherlands cant build polder

### ISSUE THREAD

**Issue by tdbomber** [Thalassicus/cep-bnw#22]
Both civil service and guilds have been researched but polder canot be built on any terrain.  Option to build polder does not display.

**Comment by stackpoint** [comment]
This seems to an issue with the in game documentation. The Polders in game text has not updated to state that it is now a coastal improvement instead of a marsh/flood plains one. 

It seems like Polders also can be built on any feature type on the coast. I'm not sure if there should be any restrictions against marsh, forest or jungle for them.

**Comment by Thalassicus** [comment]
I corrected the tooltip.
