### ISSUE TITLE
Tradition finisher doesn't give Indian Aqueduct replacement

### ISSUE THREAD

**Issue by Christoph-Wagner** [Thalassicus/cep-bnw#23]
3.7 pre-release
All Communitas mods but Interface improvements installed

After finishing Tradition none of my cities get Indus Sanitation, the Indian Aqueduct UB.

**Comment by stackpoint** [comment]
The tradition finisher has been changed in previous versions of the mod due to an incompatibility with UB aqueducts. It no longers provides free aqueducts and now provides +15% surplus food and +2 food per city. The accompanying text modification was accidentally deleted by me in 3.7 but the text change should be there in 3.8.
