### ISSUE TITLE
Leader buffs

### ISSUE THREAD

**Issue by Thalassicus** [Thalassicus/cep-bnw#240]
Improve the least-favorite 25% of leaders with simple buffs:

(% favorite, civ, buff)
- [x] 9.8% Iroquois: -50% cost Longhouse.
- [x] 9.8% Siam: More culture from Wat.
- [x] 8.7% Indonesia: Candi replaces Temple (was Garden).
- [x] 8.7% Indonesia: +20% strength Kris Swordsman.
- [x] 8.7% Inca: Terrace Farm requires no technology.
- [x] 8.7% Inca: Slinger has same base strength as an Archer (was 20% weaker) and ignores terrain costs.
- [x] 7.3% France: Gain a free cultural Great Person from each culture building constructed in Paris.
- [x] 7.3% France: +25% strength Musketeer.
- [x] 7.3% Songhai: Mud Pyramid Mosque replaces Shrine (was Temple).
- [x] 6.5% Huns: 50% land unit maintenance (was 75%).
- [x] 2.4% Ottomans: Double income from Tribute (internal trade routes).
- [x] 2.4% Ottomans: Barbary Port replaces Lighthouse (was Harbor).
- [x] 2.2% Brazil: Brazilwood Camps give 2 gold 1 culture (was 2 and 1).
- [x] 2.2% Brazil: 200% cultural great person rate in golden ages (was 150%).
- [x] 0.0% Ethiopia: 50% great person rate from alliances (was 10%).

**Comment by Thalassicus** [comment]
78f97d01ee85c02b8bc1d2a257f43fd12fedc849 Done with the buffs.

**Comment by AnastaseAlex** [comment]
About Ethiopia: Since the fix of the religious building (stele) that replaces the monument, Ethiopia is a religious powerhouse that gets a religion going waaaay before everyone else, and can enhance it and have the continent praying to it before the opponents get their first religion. Therefore the +50% birthrate by declaration of friendship is a bit unecessary.

About Brazil: I do not understand the change to Brazilwood.

Incas: They actually would be much more interesting if they were naturally placed near mountains.

Great changes!
