### ISSUE TITLE
Smokeless Powder

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#257]
This **Tech** is next to useless in the modded game.
The only purpose it has is to unlock the _Musketman_ unit but as it becomes obsolete within one tech, **Industrialization**, it's usefulness is not fully gained.
Closely related to this discussion is the re-instating of the _Arquebusier_ -- _Gatling Gun_ upgrade path. _(IMO this is one of the biggest causes of complaint on the forum, and was changed in the last release to settle that)_
If this is the desired upgrade path then having **Smokeless Powder** unlock the _Musketman_ and then have it redundant at **Industrialization** seems like a pointless step.
Why not just drop both the **Tech** and the _Unit_ and have _Longswords_ upgrade to either a stronger _Arqubusier_ (strength 30?) or to the _Rifleman_ at **Industrialization**
That way you research to upgrade your _Crossbowmen_ (strength 17) to _Gatling Gun_ (strength 30) and are only a couple of techs from upgrading your _Longswords_ (strength 24) to _Riflemen_ (strength 43), thus maintaining two lines of units, MELEE & RANGED at a similar pace, without the need to have older era units.

**Comment by Thalassicus** [comment]
The proximity of techs depends on research cost, not tech column. You can see this just by clicking the techs. I'll write a function to show the cumulative cost difference. It's a lot of work, but people have asked about this many times, so I figure it will be useful to demonstrate how techs are balanced.

In regards to unit paths, I've tried every suggestion everyone's ever had to organize unit roles over the past three years. I've put hundreds of hours of work into it without ever finding a consensus. If I change the roles again, someone will ask for another change, then someone else for another... it never ends! I eventually accepted there's no perfect solution that will make everyone happy. I'm exhausted on the unit roles topic. I want to spend time and energy focusing on things the community can actually agree on.

I think it goes back to the broader Civ community's disagreement over whether modern gun units are "melee" or "ranged." That's been a topic of discussion since Civ 5 released. There's multiple entrenched camps of people on the issue. When I try satisfying one group, another becomes unhappy. It's not something I can solve to everyone's satisfaction.

**Comment by GrantSP** [comment]
raw nerve + salt = pain.

I'll remove the salt, you cover that nerve. :smiley:

**Comment by GrantSP** [comment]
Don't worry about it. I get frustrated and I have been doing this for a
fraction of the time you have.
For you it must be exasperating.
Apologies.
Focus on the more productive aspects of the mod.
