### ISSUE TITLE
Rename vanguards

### ISSUE THREAD

**Issue by Thalassicus** [Thalassicus/cep-bnw#3]
Copied from old repo:

> Now that the 'Vanguard' name is no longer used alongside any units, and the errors with the table have been fixed. There is still the minor issue of the text appearing for certain types of units describing them as "Vanguard Units".
> While the actual fix is easy, what exactly should the new name(s) be?
> 
> It is not just 'spearman' type units, Modern units like XCOM are also described as 'vanguard'.
> 
> Any suggestions?

~GrantSP

<hr>

You're right that the word "vanguard" refers to units promoted with Recon 1-2 now, not a separate unit line.

The words I know to describe the units we're talking about are:

```
Infantry
Soldier
Trooper
Grunt
```

We could rename the combat class to infantry, and change the infantry unit to something more specific, like we did with the Cavalry unit (Dragoon).

**Comment by GrantSP** [comment]
We're getting into areas here where the definition of specific units doesn't really fit nicely anymore. We could rename the combatclass to something else but it still leaves us with the related situation of a unit in one class can be upgraded to a newer class and now find itself being described as something completely different.
This is related to disparate combatclasses both upgrading to the same thing.
e.g.
Longswordsman = MELEE & Crossbowman = ARCHER both upgrade to the Gatling Gun = MELEE

Scouts, spearmen, musketmen, paratroopers & XCOM are all RECON yet some unique variants are not.
Landsknecht are a pikemen variant but are classed MELEE.
Hunnic Battering Ram is spearman replacement, although it is a siege weapon and is classed as RECON, because of the spearman connection. The Assyrian Battering Ram is a catapult weapon but classed as MELEE and the 2 other catapults are classes as SIEGE.

The problems, though not all our doing, are exacerbated when specific promotions being applicable to specific CLASSES are then not carried over upon upgrade. Additionally the current upgrade paths are somewhat counter-intuitive, in that your expected type of unit becomes something else unexpected. Based on other unit's upgrades.

I know this has been hashed over many, many times before but could this be examined again?

**Comment by Thalassicus** [comment]
I think of how I use units. I use crossbows for long range attack, and gatling guns for short range defense. This is the only non-unique unit I know whose upgrade significantly changes my tactics. It's a Firaxis change which seems to work okay, so I'm not too worried about it.

Some units change role in more subtle ways. I use both longswords and gatling guns for short range attack/defense, so upgrading them doesn't change my strategy. These have more similar roles than crossbow-gatling. A slightly more significant change is chariots (short range attack) upgrading to knights (short range attack/defense). This upgrade is less dramatic than in the unmodded game where chariots have a long range attack.

I like when my tactics change from upgrades. It's less exciting if we follow the same combat tactics through the whole game. Mastering the early game would carry over into the late game.

I simplified things a bit by merging some units (sentry+spear) and promotions (trenches+shock). I considered merging other promotions like Accuracy+Shock, so there's one promotion that improves open terrain combat for any unit. However, people felt I was starting to simplify the game too much, so I stopped here.

**Comment by GrantSP** [comment]
I guess the crux of my argument is not with tactics but descriptions.
Is this a minor point? Possibly. But since the UI provides so much feedback as to what the unit is/does, it shows us the user wants to have information related to the units reflect what they actually do not just what they are or what they become.
Advanced users will easily grasp the concept of units described one way being used differently in later periods, new & average users may not. If we are going to classify anything then we should help the users become conversant with those terms and not introduce anomalies.
This in it itself warrants attention without the added issue of promotions a user might expect to carry over, now not being available because of role change.
My question also goes to what exactly is the "enhancement to gameplay" by these changes?
Tweaking unit values like strength and movement, or providing new and improved promotions, yes, they are enhancements. Are manipulating upgrade paths or combat classes enhancements?
Is the product offered by us matching the description on the box?

If you like we can close this and move it to a more "general forum", or not. Your choice as lead. I'll not push it any further.
