### ISSUE TITLE
Ottoman UA not working

### ISSUE THREAD

**Issue by stackpoint** [Thalassicus/cep-bnw#34]
I believe the Ottoman UA is not coded. 

I'm moving this issue from the old CEG repo to this one. See the following for more detail:

https://github.com/Thalassicus/ceg/issues/15
http://forums.civfanatics.com/showthread.php?t=515453

**Comment by Thalassicus** [comment]
Each internal trade route to an Ottoman city should add a copy of the "Tribute" building, which gives 5 gold.

I believe getting that gold "from" the trade route itself would require a game core mod, but the end result should be the same.

**Comment by GrantSP** [comment]
Then the issue is one of conveying that information to the user correctly.
As it stands now there is no feedback to the user/player as to the Gold being added.
They have no idea of the "dummy" building and how it works.

What code is in place to remove the building after the trade route is gone?
It should only exist for as long as the route is available, or are you describing ALL routes that exist when cities are connected, not those specifically picked with a caravan or cargo ship?

I, and I suspect everyone else, believe it is the latter. There needs to be feedback as to the Gold income WHILST the route exists.

**Comment by Thalassicus** [comment]
It looks like the problem was simple - the Ottomans did not have code to set them to the new trait. I added this to CEL__J_Z.xml, and it appears to work now.

``` xml
    <Leader_Traits>
        <Update>
            <Where LeaderType="LEADER_SULEIMAN" />
            <Set TraitType="TRAIT_TRIBUTE" />
        </Update>
    </Leader_Traits>
```

I also made the income scale by era, so it now gives (5 + 2*era) gold in the destination city of internal trade routes. The gold updates at the start and end of each turn.

The basic principle is the Ottomans can use internal trade routes instead of foreign trade, and still get about the same amount of gold.
