### ISSUE TITLE
Inca workers do not build terrace farms.

### ISSUE THREAD

**Issue by AnastaseAlex** [Thalassicus/cep-bnw#36]
Even in the late game inca workers do not seem to be building terrace farms.

**Comment by GrantSP** [comment]
Perhaps a some data to support your assertion is needed. 
Even when there appears to be a bug it may often be put down to some other routine the AI is following. 
I was just finishing a game where one of the opponents was Inca, and they were building right up till the industrial age. Only stopped because of nowhere to build them.

**Comment by AnastaseAlex** [comment]
I will test it some more times to make sure, and if it persist I will reopen this.

**Comment by GrantSP** [comment]
Ahh I only saw the email for the original post. Sorry. If it doesn't show
up in normal gaming, don't bother testing for it. Leave it closed.
