### ISSUE TITLE
City-State greetings

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#40]
In vanilla the greeting reflects a change of the gift depending on whether you are the first to meet this city-state or not. 30 gold if you are and 15 if not.

With the mod activated the greeting still shows a distinction between who met them first or not but the described gift is the same. Or sometimes there is no greeting display at all and nothing is exchanged.

What exactly is the desired result?
Are these CSs supposed to give the same gifts to all they meet or not?
Is there times when the greeting display panel is not supposed to display?

I would like to see some sort of diplomatic boost given for being the first, and hence probably the closest, civ to meet them. Maybe an instant and permanent +20 to the standing. The gold gifts are pretty useless.

**Comment by Hawawaa** [comment]
For the first part, with BNW early gold is tighter so keep the 30 gold on meeting CSs. (Soon we will have Stories/random events back and that's a whole other thing to bring up for early game gold since gold mid-late game gold is so easy to come by but I'll bring that up later)

Now I have noticed when meeting CSs for the first time the pop up box doesn't always pop up and sometimes I don't always get my free stuff. I do believe this is a bug. 

I'm down for a 10-20+ standings for being first or being the closest to a CS.

**Comment by AnastaseAlex** [comment]
The early gold is important in many of my games, incentivizing building scouts to explore and helping out with the first worker. I would also like the +10 permanent standing idea.

**Comment by Hawawaa** [comment]
Ok +10 permanent standings for being 1st and a +10 for finding them ie less messages of you sending your units through their territory and CSs getting mad. A permanent +10 stands for city states that are closest to you ie certain range. Early game they are easily yours but late game well everyone's throwing money and spy's so that can shake things up.

**Comment by Thalassicus** [comment]
I made exploration more desirable by increasing the gold from meeting citystates second. The person who meets a CS first gets gold earlier than others, which can be spent earlier to improve our empire. That's a powerful advantage to exploring first. Giving later people more gold increases the incentive to continue exploring beyond our close neighborhood. It also reduces the effect of random bad luck in the early game.

**Comment by GrantSP** [comment]
Ok, so it boils down to a minor display thing of what the actual greeting message shows.
The extra diplo bonuses can wait for another time.

**Comment by GrantSP** [comment]
Changed the text to not make a distinction between the first to meet or not.
