### ISSUE TITLE
Sea Beggar not visible in Tech Tree as Netherlands

### ISSUE THREAD

**Issue by kylorn** [Thalassicus/cep-bnw#46]
I don't know if you can build it once it's researched, but it's not in the tech tree.

**Comment by skodkim** [comment]
Maybe a stupid question but are you playing the Dutch? Otherwise it isn't visible.

Which version are you running? Other mods?

\Skodkim

**Comment by kylorn** [comment]
![capture](https://f.cloud.github.com/assets/6125530/1695525/c5b402be-5eb3-11e3-9129-a09b6ae4e267.JPG)

Playing the new 3.9

**Comment by stackpoint** [comment]
I believe the Dutch no longer has the sea beggar as an UU.

**Comment by kylorn** [comment]
Then they should have the Galleon in its place instead, like the other Civs.

**Comment by stackpoint** [comment]
To resolve:
- [x] Remove the Sea Begger from the Netherlands in the Civilization selection screen
- [x] Remove the Sea Begger from the Netherlands introductory splashscreen
- [x] Remove the Sea Begger from the Civiliopedia
- [x] Add the Galleon back

**Comment by GrantSP** [comment]
Ok, the problem here was the original design choices for the Dutch was to remove the Sea Beggar and replace it with an unique variant of the Caravansary that doubles luxuries and increases the trade distance by 50%.

The new building is now defined and implemented and the trade distance is set at 50% more than normal.
I will have to do a bit of lua magic I think to set the double luxuries. This will be done later. At the moment I will upload the changes as they stand.
