### ISSUE TITLE
Spreadsheet documentation

### ISSUE THREAD

**Issue by Thalassicus** [Thalassicus/cep-bnw#6]
Move spreadsheet documentation from the project folders to Google Drive.

**Comment by GrantSP** [comment]
If by spreadsheet documentation you mean those pages used to auto-generate the sql, then that may be more difficult than it looks. I am not 100% sure Google Sheets has direct copies of all the functions used in those sheets.

You will of course have to set up an account with Google that gives all those involved public access to those documents. But you probably knew that.

I will try moving some sheets to my drive and see if they still work.

**Comment by GrantSP** [comment]
This may prove more of a hindrance than a help.

The macros and formulae used in the spreadsheets will need to be modified to work properly. Not to mention the lack of formatting options currently available with Google Sheets. No text orientation for a start.
Inside the Google Drive, if the files are stored as OpenDocument files there are 3 viewer options.
1) Google Drive Viewer which fails and asks to download it instead or
2) A third party viewer called OpenDocument Reader which, although it does open, only presents a single page of ALL the tabs joined together in one long document. Very poor for our purposes.
3) If the spreadsheets are converted to Google Sheets then they 'may' still function as templates for the sql generation. They are much more readable as spreadsheets, retain some formatting, like colours and boxes etc. but
the proviso here is STRJOIN is not supported, and since it is used extensively in them this may be a problem.

Other 'cloud storage' is no better. Even Microsoft's SkyDrive requires converting Microsoft's own *.xls files so they can be read yet they too stumble over STRJOIN. DropBox, CloudDrive and others fare no better.

I have loaded a file [here](https://docs.google.com/spreadsheet/ccc?key=0AsRvXltL5NgddFJvc1kxTDBzbWhGTElTMDNRalczZVE&usp=sharing) to show how a Google Sheets version of one of our files looks like.

**Comment by Thalassicus** [comment]
I thought this through for some time. The advantages are:
- Easier collaboration doesn't need github, and avoids sync problems with github binary files.
- Easier viewing without excel or libreoffice.
- One place for all data. It's tough to figure out if the "leaders & AI" spreadsheet goes in the cat or ceg project, for example.
- Drive has a JOIN function unlike excel or libreoffice. We won't need a macro anymore. Macros concern security-conscious people.
- People can maintain the data more easily after I'm gone from the project.

The [folder](https://drive.google.com/#folders/0B58Ehya83q19eVlvWXdmLXZ6UUE) on drive lets anyone view with a link. Edits require joining the [CommunitasExpansion](https://groups.google.com/forum/#!forum/communitasexpansion) group. Please join this group. It's open to anyone. I don't expect problems with vandalism, but drive tracks version history so vandalism edits can be undone. This is similar to the wiki. The editing group can be made invite-only if it becomes necessary in the future.

**Comment by Thalassicus** [comment]
I copied the CEP_Language sheet into google docs today and discovered something awesome! Google sheets has a "googletranslate" function; you can probably guess what we can use that for!

I'm configuring our language files to automatically translate everything into every language. The machine translations won't be perfect, but will at least provide basic localization. This will drastically reduce the work for human translators. Anyone who notices a bug can simply go to the google doc, fix the mistake, and it'll get included in the next project update.
