### ISSUE TITLE
[3.10.1] Building errors

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#74]
Some may be intended...
- The English Stem Mill UB only cost a third of the Factory which it replaces
- The English Stem Mill UB unlocks 2 ideologies while the Factory which it replaces unlocks 3 - not a great choice for a UB
- Workshop (BUILDINGCLASS_WINDMILL) and Smith
  (BUILDINGCLASS_WORKSHOP) are lacking TXT_KEY_BUILDING_###_PEDIA entries
- Workshops (BUILDINGCLASS_WINDMILL) are unlocked very late (Steam Power) and are very cheap compared to other Buildings from this tier. Intended (I think it should be much earlier - perhaps Engineering)?

\Skodkim

**Comment by AnastaseAlex** [comment]
I thought the factory also unlocked 2 ideologies. I will have to check it out tonight.

**Comment by skodkim** [comment]
In Steam\steamapps\common\sid meier's civilization v\Assets\DLC\Expansion2\Gameplay\XML\Buildings\CIV5Buildings.xml it is set to 3. This isn't changed in CEP.

**Comment by GrantSP** [comment]
The TXT_KEY errors are now fixed. They are the result of SMITH being incorrectly referred to as SMITHY and the WORKSHOP pedia entry being changed to a general version instead of the TXT_KEY_CIV5_BUILDINGS_WORKSHOP_TEXT entry it is referred to in Cat_Buildings.xml.

Totally agree with you about the workshop. It is a building that sits out of time in regards to what it does and when.
There are no Production buildings in the Classical era so it could/should be moved there. Also the Smith, available in at Bronze Working, costs more to build and does pretty much the same job as the Smith! The smith also gives a slot for an engineer and doesn't have a restriction as to where it can be built, unlike the Workshop with a not on a hill. This last point no doubt comes from it being a modded Windmill.

The 2 or 3 ideologies observation is also correct. Factories have 3 and the Steam Mill only 2. Corrected.
Likewise the cost. It is also lacking a Coal necessity that the Factory has or the Smith requirement of the Factory.
I have added these in and if incorrect they can be easily removed.
